

export const RESPONSE = {
  PROFILE_UPDATE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  PICTURE_ADD_SUCCESS: "PICTURE_ADDED_SUCCESS",
  PICTURE_DELETE_SUCCESS: "PICTURE_DELETE_SUCCESS",
  PICTURE_UPDATE_SUCCESS: "PICTURE_EDIT_SUCCESS",
};
