/**
 * 
 * Copyright 2009-2021 Blue Shark Solution Inc
 * @author bssinc
 */

export const RESPONSES = {
  RESEND_EMAIL: "YOUR_EMAIL_HAS_NOT_BEEN_VERIFIED",
  EMAIL_VERIFIED: "EMAIL_HAS_BEEN_SUCCESSFULLY_VERIFIED",
  UNEXPECTED_ERROR: "Some Error Occurred, Please Try Again Later",
  TAMPERED_LINK: "VERIFICATION_CODE_HAS_BEEN_EXPIRED",
  EXPIRED_LINK: "THE_LINK_YOU_ARE_TRYING_TO_ACCESS_HAS_BEEN_TEMPERED",
  OTP_SENT: "VERIFICATION_CODE_SENT_TO_YOUR_REGISTERED_EMAIL",
  OTP_VERIFIED: "VERIFICATION_CODE_HAS_SUCCESSFULLY_VERIFIED",
  EMAIL_EXIST: "EMAIL_EXIST",
  EMAIL_SENT: "EMAIL_HAS_BEEN_SENT_SUCCESSFULLY_PLEASE_VERIFY_IT_TO_PROCEED",
  EMAIL_PASSWORD_INCORRECT: "EMAIL_PASSWORD_INCORRECT",
};
